[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash -s 16mb --partition-table partitions.csv --monitor"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32s3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.2.3"

ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"

[alias]
flash-srmodels = "make flash-srmodels"
flash-all = "make flash-all"
